### ISSUE TITLE
Mounted binary not found in container when using volume with Docker Compose

### ISSUE THREAD

**Issue by wanghe-fit2cloud** [supercorp-ai/supergateway#40]
### Description

I'm trying to run a custom binary called `mcp-1panel` via Docker Compose.  The binary exists on the host at `/usr/local/bin/mcp-1panel`.

Here is the relevant part of my `docker-compose.yml`:

```yaml
services:
  mcp-1panel:
    image: supercorp/supergateway:latest
    container_name: mcp-1panel
    restart: unless-stopped
    networks:
      - 1panel-network
    ports:
      - 8086:8086
    environment:
      PANEL_ACCESS_TOKEN: zYOVKKd7H0Ruo2XY4dGHhpSR0w6TK1A4
      PANEL_HOST: http://my_ip:port
    command:
      - --stdio
      - /usr/local/bin/mcp-1panel
      - --port
      - 8086
      - --baseUrl
      - http://base_url
      - --ssePath
      - /1panel
      - --messagePath
      - /1panel/messages
    volumes:
      - /usr/local/bin/mcp-1panel:/usr/local/bin/mcp-1panel
networks:
  1panel-network:
    external: true
```

The container failed to start with the following error:
```
mcp-1panel  | [supergateway] Child stderr: /bin/sh: /usr/local/bin/mcp-1panel: not found
```

However, when I mounted the same binary file into a container started normally via the npx command, I confirmed that the file existed and its permissions were correct.

**Comment by Nedomas** [comment]
Thanks, looks weird, should work - will try to repro over the coming few days and write an update here. Please let me know if you figure it out in the meantime

**Comment by wanghe-fit2cloud** [comment]
Thank you very much! I also tried running other MCP Servers that support Docker commands using the Docker-in-Docker approach, but encountered the same error: docker: not found.

**Comment by Nedomas** [comment]
@wanghe-fit2cloud I think something is very peculiar with your Docker configuration. My feel that this is not related to Supergateway.

I tried with `docker-compose.yml` which is exactly as your’s except `8086` in `command` is `"8086"` (because my Docker errored on that) and I don’t have your real `/usr/local/bin/mcp-1panel` file so I just created one like.

This is `./mcp-1panel-test` (with `chmod +x mcp-1panel-test`):
```sh
#!/bin/sh
echo "Hello from our mcp-1panel!"
```

This is my `docker-compose.yml`:
```yml
services:
  mcp-1panel:
    image: supercorp/supergateway:latest
    container_name: mcp-1panel
    restart: unless-stopped
    networks:
      - 1panel-network
    ports:
      - 8086:8086
    environment:
      PANEL_ACCESS_TOKEN: zYOVKKd7H0Ruo2XY4dGHhpSR0w6TK1A4
      PANEL_HOST: http://my_ip:port
    command:
      - --stdio
      - /usr/local/bin/mcp-1panel
      - --port
      - "8086"
      - --baseUrl
      - http://base_url
      - --ssePath
      - /1panel
      - --messagePath
      - /1panel/messages
    volumes:
      - ./mcp-1panel-test:/usr/local/bin/mcp-1panel
networks:
  1panel-network:
    external: true
```

When I run it, I can confirm it works as expected:
```sh
domas@MacBookPro test % docker -v
Docker version 28.0.1, build 068a01e

domas@MacBookPro test % docker compose up
[+] Running 1/1
 ✔ Container mcp-1panel  Recreated                                                                                                                               0.1s
Attaching to mcp-1panel
mcp-1panel  | [supergateway] Starting...
mcp-1panel  | [supergateway] Supergateway is supported by Superinterface - https://superinterface.ai
mcp-1panel  | [supergateway]   - port: 8086
mcp-1panel  | [supergateway]   - stdio: /usr/local/bin/mcp-1panel
mcp-1panel  | [supergateway]   - baseUrl: http://base_url
mcp-1panel  | [supergateway]   - ssePath: /1panel
mcp-1panel  | [supergateway]   - messagePath: /1panel/messages
mcp-1panel  | [supergateway]   - CORS enabled: false
mcp-1panel  | [supergateway]   - Health endpoints: (none)
mcp-1panel  | [supergateway] Listening on port 8086
mcp-1panel  | [supergateway] SSE endpoint: http://localhost:8086/1panel
mcp-1panel  | [supergateway] POST messages: http://localhost:8086/1panel/messages
mcp-1panel  | [supergateway] Child non-JSON: Hello from our mcp-1panel!
mcp-1panel  | [supergateway] Child exited: code=0, signal=null
mcp-1panel exited with code 0
```

Could you try to do the same and validate that my test setup works for you? Maybe then you could replace it with the original `/usr/local/bin/mcp-1panel` file and recheck if it works?

I guess maybe the port thing was an a real error here, but your Docker env did not show the right error? Let me know if you figure it out so that we can close this when it’s done. Thanks!
